== Stale IPFS

This is a list of no longer maintained awesome IPFS projects. This list
is kept around as a resource for reference. If you find your project on
this list and you feel it should be on the link:./README.md[Awesome
List], submit a pr and we’ll get it in the right place.

=== Table of Contents

* link:#apps[Apps]
* link:#tools[Tools]

=== Apps

* https://github.com/airsecure/airsecure[AirSecure] - Decentralized two
factor authentication app built on Textile & IPFS.
* https://github.com/MichaelMure/Arbore[Arbore] - A friend-to-friend
file-sharing app build on top of IPFS.
* https://github.com/RTradeLtd/ipcoronafs[ipcoronafs] - A realtime
service to scrape COVID-19 and SARS-CoV-2, storing on IPFS, DNSLink, and
streaming over LibP2P pubsub
* https://github.com/ipfs-search/ipfs-search[ipfs-search] - IPFS search
engine Sniffs the DHT gossip and indexes file and directory hashes.
Metadata and search APIs available.

=== Tools

* https://github.com/RHazDev/Sweet-IPFS[Sweet IPFS] - Full node for
Android.
* https://github.com/meyer1994/ipgit[IPGit] - Remote Git repository that
mirrors your code to IPFS.
** Note: @bmann Heroku endpoint in repo shows application error
https://ipgit.herokuapp.com/
** Not really an app
** It _is_ super cool and I’d love to see more IPFS + git stuff like
this (maybe we can get Gitea or ForgeJo supporting IPFS)
