# SPDX-License-Identifier: CC0-1.0

name: Pull request workflow

on:
  pull_request_target:
    types: [opened, synchronize, reopened]
    branches: [master, main]

permissions:
  contents: read

jobs:
  link-check:
    runs-on: ubuntu-latest
    if: "!contains(github.event.head_commit.message, '[skip ci]')"
    steps:
      - name: Checkout
        uses: actions/checkout@a37ce9120846195fa4ece8f58b268e6043cb2f26 # v3
      - name: Check README links
        uses: lycheeverse/lychee-action@e7477775783ea5526144ba13e8db5eec57747ce8 # v2.9.0
        with:
          args: >-
            README.md
            --exclude-mail
            --exclude 'ipfs\\.io'
            --accept 200,429
          fail: true
